name: GitHub-Hosted PCellTests

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  pcell-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v3

      - name: Run xhost command
        run: xhost +local:docker

      - name: Login to GitHub Container Registry 
        run: echo ${{ secrets.CR_PAT }} | podman login ghcr.io -u farihais --password-stdin

      - name: Pull docker image 
        run: docker pull ghcr.io/farihais/gha_klayout:latest

      - name: Run docker container from image
        run: |
                docker run -itd --name test ghcr.io/farihais/gha_klayout:latest
                
      - name: Run KLayout Python script inside container 
        run: docker exec test klayout -z -r EBeam_Lib_PCellTests.py

      - name: Copy pymacros folder to docker container
        run: docker cp $GITHUB_WORKSPACE/klayout/EBeam/pymacros test:/home/pymacros

      - name: Run KLayout Python script inside container and capture the exit code 
        run: docker exec test /klayout-0.28.12/bin-release/klayout -zz -r pymacros/EBeam_Lib_PCellTests.py || echo "KLAYOUT_EXIT_CODE=$?" >> $GITHUB_ENV
        continue-on-error: true

      - name: Stop the container and remove it 
        run: |
                docker stop self_hosted_test
                docker rm self_hosted_test

      - name: Fail the job if exit code is non-zero
        run: |
                if [ $KLAYOUT_EXIT_CODE -ne 0 ]; then
                        echo "KLayout exited with non-zero exit code"
                        exit 1
                fi 
