name: EBeam Tests Coverage

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  ebeam-tests-coverage:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install coverage

      - name: Run KLayout Python script with coverage
        run: |
          coverage run --source=. $GITHUB_WORKSPACE/klayout/EBeam/pymacros/EBeam_Lib_PCellTests.py
        continue-on-error: true

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
