name: GitHub-Hosted PCellTests

on:
  push:
    branches:
      - master

jobs:
  pcell-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v3

      - name : Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10.9'

      - name: Login to GitHub Container Registry
        run: echo ${{ secrets.CR_PAT }} | docker login ghcr.io -u farihais --password-stdin

      - name: Pull docker image 
        run: docker pull ghcr.io/farihais/gha_klayout:latest

      - name: Run docker container from image
        run: docker run -itd --name test_klayout -e DISPLAY=unix$DISPLAY -v /tmp/.X11-unix:/tmp/.X11-unix ghcr.io/farihais/gha_klayout:latest

      - name: Run KLayout Python script inside container 
        run: docker exec test_klayout klayout -z -r EBeam_Lib_PCellTests.py
