name: Lumerical PCell Tests

on:
  push:
    branches:
      - master

jobs:
  pcell-test:
    runs-on: self-hosted 

    steps:
      - name: Checkout the code
        uses: actions/checkout@v3

      - name: Run xhost command
        run: xhost +local:docker

      - name: Login to GitHub Container Registry
        run: echo ${{ secrets.CR_PAT }} | docker login ghcr.io -u farihais --password-stdin

      - name: Pull docker image
        run: sudo docker pull ghcr.io/farihais/gha_lumerical:latest

      - name: Run docker container from image
        run: sudo docker run -itd --name test_lumerical -e DISPLAY=unix$DISPLAY -v /tmp/.X11-unix:/tmp/.X11-unix ghcr.io/farihais/gha_lumerical:latest

      - name: Run KLayout Python script inside container 
        run: sudo docker exec test_lumerical klayout -z -r EBeam_Lib_PCellTests.py
