name: PCell Tests

on:
  push:
    branches:
      - master

jobs:
  pcell-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v3

      - name : Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10.9'

      - name: Install Python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run the EBeam_Lib_PCellTests script
        run: python3 /klayout/EBeam/pymacros/EBeam_Lib_PCellTests.py