name: PCell Tests

on:
  push:
    branches:
      - master

jobs:
  pcell-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v3

      - name : Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10.9'

      - name: Install Python packages
        run: |
          python -m pip install --upgrade pip

      - name: Login to GitHub Container Registry
        run: |
           echo --- Logging in to ghcr.io ---
           echo ${{ secrets.CR_PAT }} | docker login ghcr.io -u farihais --password-stdin

      - name: Pull docker image 
        run: |
          echo --- Pulling docker image ---
          docker pull ghcr.io/farihais/gha_klayout:latest

      - name: Run docker container from image
        run: |
          echo --- Building docker container ---
          docker run -it --name test -e DISPLAY=unix$DISPLAY -v /tmp/.X11-unix:/tmp/.X11-unix ghcr.io/farihais/gha_klayout:latest

      - name: Run the EBeam_Lib_PCellTests script with KLayout
        run: bash -c 'klayout -e -r ../../klayout/EBeam/pymacros/EBeam_Lib_PCellTests.py'
