name: Lumerical PCell Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'

jobs:
  pcell-test:
    runs-on: self-hosted 

    steps:
      - name: Checkout the code
        uses: actions/checkout@v3

      - name: Run xhost command
        run: xhost +local:docker

      - name: Login to GitHub Container Registry 
        run: echo ${{ secrets.CR_PAT }} | podman login ghcr.io -u farihais --password-stdin

      - name: Pull fotonika image
        run: podman pull ghcr.io/siepic/fotonika-env:00.01.00

      - name: Run podman container from image
        run: podman run -itd --name self_hosted_test -e DISPLAY -v /tmp/.X11-unix:/tmp/.X11-unix --security-opt label=type:container_runtime_t ghcr.io/farihais/gha_lumerical:latest

      - name: Run KLayout Python script inside container 
        run: podman exec self_hosted_test klayout -z -r EBeam_Lib_PCellTests.py
