name: Self-Hosted PCellTests

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  pcell-tests:
    runs-on: self-hosted 

    steps:
      - name: Checkout the code
        uses: actions/checkout@v3

      - name: Run xhost command
        run: xhost +local:docker

        #      - name: Login to GitHub Container Registry 
        #        run: echo ${{ secrets.CR_PAT }} | podman login ghcr.io -u farihais --password-stdin
        #
        #      - name: Pull fotonika image
        #        run: podman pull ghcr.io/siepic/fotonika-env:0.01.00
        #
      - name: Run podman container from image
        run: podman run -itd --name self_hosted_test -e DISPLAY -v /tmp/.X11-unix:/tmp/.X11-unix --security-opt label=type:container_runtime_t ghcr.io/siepic/fotonika-env:0.01.00

      - name: Copy pymacros folder to podman container
        run: |
                #                podman cp $GITHUB_WORKSPACE/klayout/EBeam/pymacros/pcells_EBeam self_hosted_test:/home/pcells_EBeam
                #                podman cp $GITHUB_WORKSPACE/klayout/EBeam/pymacros/EBeam_Lib_PCellTests.py self_hosted_test:/home/EBeam_Lib_PCellTests.py
                #                podman cp $GITHUB_WORKSPACE/klayout/EBeam/pymacros/custom_exceptions.py self_hosted_test:/home/custom_exceptions.py
                podman cp $GITHUB_WORKSPACE/klayout/EBeam/pymacros self_hosted_test:/home/pymacros

      - name: Run KLayout Python script inside container 
        run: |
                podman exec self_hosted_test /klayout-0.28.12/bin-release/klayout -z -r pymacros/EBeam_Lib_PCellTests.py

      - name: Capture exit code from container
        run: |
                EXIT_CODE=$(podman exec self_hosted_test /bin/sh -c "echo $?")
                echo "Exit code: $EXIT_CODE"
                echo "SCRIPT_EXIT_CODE=$EXIT_CODE" >> $GITHUB_ENV

      - name: Stop the container and remove it and fail the job if exit code is non-zero
        run: |
                podman stop self_hosted_test
                podman rm self_hosted_test
                
                if [ $SCRIPT_EXIT_CODE -ne 0 ]; then
                        echo "Script exited with non-zero exit code"
                        exit 1
                fi 
